[diff]
  tool = vimdiff
[difftool]
    prompt = false
[difftool "vimdiff"]
    # unset GIT_EXTERNAL_DIFF, to allow :!git diff to work
    # unset GIT_DIR and GIT_WORK_TREE, because it confuses GitSigns badly
    # The `vim` command is the same that git would use by default, except
    # missing a -R (readonly) option.
  #cmd = echo LOCAL=$LOCAL\\\\nREMOTE=$REMOTE\\\\nMERGED=$MERGED\\\\nBASE=$BASE
  # NOTE: $MERGED is incorrectly set to the non-existant old path when diffing a move
  cmd = set -x && env \
      --unset=GIT_EXTERNAL_DIFF \
      --unset=GIT_DIR \
      --unset=GIT_WORK_TREE \
      --chdir=\"$GIT_PREFIX\" \
      $EDITOR -f -d -c \"wincmd l\" \"$LOCAL\" \"$( \
        realpath -mL --relative-to=\"$GIT_PREFIX\" \"$REMOTE\" \
      )\"
      # or maybe:
      #   vim -f -d -c \"wincmd l\" \"$LOCAL\" \"$GIT_PREFIX/$MERGED\"
[alias]
  vimdiff = difftool
