lvim.builtin = {
  alpha = {
    active = true,
    dashboard = {
      config = {},
      opts = {
        autostart = true,
      },
      section = {
        buttons = {
          entries = {
            { "f", "󰈞  Find File", "<CMD>Telescope find_files<CR>" },
            { "n", "  New File", "<CMD>ene!<CR>" },
            { "p", "  Projects ", "<CMD>Telescope projects<CR>" },
            { "r", "  Recent files", ":Telescope oldfiles <CR>" },
            { "t", "󰊄  Find Text", "<CMD>Telescope live_grep<CR>" },
            { "c", "  Configuration", "<CMD>edit /home/bukzor/.config/lvim/config.lua <CR>" },
            { "q", "󰅖  Quit", "<CMD>quit<CR>" },
          },
          opts = {
            hl_shortcut = "Include",
            spacing = 1,
          },
        },
        footer = {
          opts = {
            hl = "Number",
            position = "center",
          },
          type = "text",
          val = { "       ", " lunarvim.org", "master-15dc5292" },
        },
        header = {
          opts = {
            hl = "Label",
            position = "center",
          },
          type = "text",
          val = "<function 1>",
        },
      },
    },
    mode = "dashboard",
    startify = {
      config = {},
      opts = {
        autostart = true,
      },
      section = {
        bottom_buttons = {
          entries = {
            { "q", "Quit", "<CMD>quit<CR>" },
          },
        },
        footer = {
          type = "group",
        },
        header = {
          opts = {
            hl = "Label",
            shrink_margin = false,
          },
          type = "text",
          val = { "    __                          _    ___         ",
            "   / /   __  ______  ____ _____| |  / (_)___ ___ ", "  / /   / / / / __ \\/ __ `/ ___/ | / / / __ `__ \\",
            " / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /", "/_____/\\__,_/_/ /_/\\__,_/_/    |___/_/_/ /_/ /_/ " },
        },
        top_buttons = {
          entries = {
            { "e", " New File", "<CMD>ene!<CR>" },
          },
        },
      },
    },
  },
  autopairs = {
    active = true,
    check_ts = true,
    disable_filetype = { "TelescopePrompt", "spectre_panel" },
    disable_in_macro = false,
    disable_in_visualblock = false,
    enable_afterquote = true,
    enable_check_bracket_line = false,
    enable_moveright = true,
    fast_wrap = {
      chars = { "\123", "[", "(", '"', "'" },
      check_comma = true,
      end_key = "$",
      highlight = "Search",
      highlight_grey = "Comment",
      keys = "qwertyuiopzxcvbnmasdfghjkl",
      map = "<M-e>",
      offset = 0,
      pattern = "[%'%\"%)%>%]%)%\123%,]",
    },
    ignored_next_char = "[%w%%%'%[%\"%.]",
    map_bs = true,
    map_c_w = false,
    map_char = {
      all = "(",
      tex = "\123",
    },
    ts_config = {
      java = false,
      javascript = { "string", "template_string" },
      lua = { "string", "source" },
    },
  },
  bigfile = {
    active = true,
    config = {},
  },
  breadcrumbs = {
    active = true,
    options = {
      depth_limit = 0,
      depth_limit_indicator = "..",
      highlight = true,
      icons = {
        Array = " ",
        Boolean = " ",
        Class = " ",
        Color = " ",
        Constant = " ",
        Constructor = " ",
        Enum = " ",
        EnumMember = " ",
        Event = " ",
        Field = " ",
        File = " ",
        Folder = "󰉋 ",
        Function = " ",
        Interface = " ",
        Key = " ",
        Keyword = " ",
        Method = " ",
        Module = " ",
        Namespace = " ",
        Null = "󰟢 ",
        Number = " ",
        Object = " ",
        Operator = " ",
        Package = " ",
        Property = " ",
        Reference = " ",
        Snippet = " ",
        String = " ",
        Struct = " ",
        Text = " ",
        TypeParameter = " ",
        Unit = " ",
        Value = " ",
        Variable = " ",
      },
      separator = "  ",
    },
    winbar_filetype_exclude = { "help", "startify", "dashboard", "lazy", "neo-tree", "neogitstatus", "NvimTree",
      "Trouble", "alpha", "lir", "Outline", "spectre_panel", "toggleterm", "DressingSelect", "Jaq", "harpoon",
      "dap-repl", "dap-terminal", "dapui_console", "dapui_hover", "lab", "notify", "noice", "neotest-summary", "" },
  },
  bufferline = {
    active = true,
    highlights = {
      background = {
        italic = true,
      },
      buffer_selected = {
        bold = true,
      },
    },
    keymap = {
      normal_mode = {},
    },
    options = {
      always_show_bufferline = false,
      buffer_close_icon = "󰅖",
      close_command = "<function 2>",
      close_icon = "",
      color_icons = true,
      custom_filter = "<function 3>",
      diagnostics = "nvim_lsp",
      diagnostics_indicator = "<function 4>",
      diagnostics_update_in_insert = false,
      enforce_regular_tabs = false,
      hover = {
        delay = 200,
        enabled = false,
        reveal = { "close" },
      },
      indicator = {
        icon = "▎",
        style = "icon",
      },
      left_mouse_command = "buffer %d",
      left_trunc_marker = "",
      max_name_length = 18,
      max_prefix_length = 15,
      mode = "buffers",
      modified_icon = " ",
      name_formatter = "<function 5>",
      numbers = "none",
      offsets = {
        {
          filetype = "undotree",
          highlight = "PanelHeading",
          padding = 1,
          text = "Undotree",
        },
        {
          filetype = "NvimTree",
          highlight = "PanelHeading",
          padding = 1,
          text = "Explorer",
        },
        {
          filetype = "DiffviewFiles",
          highlight = "PanelHeading",
          padding = 1,
          text = "Diff View",
        },
        {
          filetype = "flutterToolsOutline",
          highlight = "PanelHeading",
          text = "Flutter Outline",
        },
        {
          filetype = "lazy",
          highlight = "PanelHeading",
          padding = 1,
          text = "Lazy",
        },
      },
      persist_buffer_sort = true,
      right_mouse_command = "vert sbuffer %d",
      right_trunc_marker = "",
      separator_style = "thin",
      show_buffer_close_icons = true,
      show_buffer_icons = true,
      show_close_icon = false,
      show_tab_indicators = true,
      sort_by = "id",
      tab_size = 18,
      truncate_names = true,
    },
  },
  cmp = {
    active = true,
    cmdline = {
      enable = false,
      options = {
        {
          sources = {
            {
              name = "path",
            },
            {
              name = "cmdline",
            },
          },
          type = ":",
        },
        {
          sources = {
            {
              name = "buffer",
            },
          },
          type = { "/", "?" },
        },
      },
    },
    completion = {
      keyword_length = 1,
    },
    confirm_opts = {
      behavior = "replace",
      select = false,
    },
    enabled = "<function 6>",
    experimental = {
      ghost_text = false,
      native_menu = false,
    },
    formatting = {
      duplicates = {
        buffer = 1,
        luasnip = 1,
        nvim_lsp = 0,
        path = 1,
      },
      duplicates_default = 0,
      fields = { "kind", "abbr", "menu" },
      format = "<function 7>",
      kind_icons = {
        Array = "",
        Boolean = "",
        Class = "",
        Color = "",
        Constant = "",
        Constructor = "",
        Enum = "",
        EnumMember = "",
        Event = "",
        Field = "",
        File = "",
        Folder = "󰉋",
        Function = "",
        Interface = "",
        Key = "",
        Keyword = "",
        Method = "",
        Module = "",
        Namespace = "",
        Null = "󰟢",
        Number = "",
        Object = "",
        Operator = "",
        Package = "",
        Property = "",
        Reference = "",
        Snippet = "",
        String = "",
        Struct = "",
        Text = "",
        TypeParameter = "",
        Unit = "",
        Value = "",
        Variable = "",
      },
      max_width = 0,
      source_names = {
        buffer = "(Buffer)",
        calc = "(Calc)",
        cmp_tabnine = "(Tabnine)",
        copilot = "(Copilot)",
        emoji = "(Emoji)",
        luasnip = "(Snippet)",
        nvim_lsp = "(LSP)",
        path = "(Path)",
        tmux = "(TMUX)",
        treesitter = "(TreeSitter)",
        vsnip = "(Snippet)",
      },
    },
    mapping = {
      ["<C-D>"] = "<function 8>",
      ["<C-E>"] = "<function 9>",
      ["<C-F>"] = "<function 10>",
      ["<C-J>"] = {
        c = "<function 11>",
        i = "<function 11>",
      },
      ["<C-K>"] = {
        c = "<function 12>",
        i = "<function 12>",
      },
      ["<C-N>"] = {
        i = "<function 13>",
      },
      ["<C-P>"] = {
        i = "<function 14>",
      },
      ["<C-Space>"] = "<function 15>",
      ["<C-Y>"] = {
        c = "<function 16>",
        i = "<function 17>",
      },
      ["<CR>"] = {
        i = "<function 18>",
      },
      ["<Down>"] = {
        i = "<function 19>",
      },
      ["<S-Tab>"] = {
        i = "<function 20>",
        s = "<function 20>",
      },
      ["<Tab>"] = {
        i = "<function 21>",
        s = "<function 21>",
      },
      ["<Up>"] = {
        i = "<function 22>",
      },
    },
  },
  snippet = {
    expand = "<function 23>",
  },
  sources = {
    {
      max_item_count = 3,
      name = "copilot",
      option = {},
      trigger_characters = {
        { ".", ":", "(", "'", '"', "[", ",", "#", "*", "@", "|", "=", "-", "\123", "/", "\\", "+", "?", " " },
      },
      {
        entry_filter = "<function 24>",
        name = "nvim_lsp",
        option = {},
      },
      {
        name = "path",
        option = {},
      },
      {
        name = "luasnip",
        option = {},
      },
      {
        name = "cmp_tabnine",
        option = {},
      },
      {
        name = "nvim_lua",
        option = {},
      },
      {
        name = "buffer",
        option = {},
      },
      {
        name = "calc",
        option = {},
      },
      {
        name = "emoji",
        option = {},
      },
      {
        name = "treesitter",
        option = {},
      },
      {
        name = "crates",
        option = {},
      },
      {
        name = "tmux",
        option = {},
      },
    },
    window = {
      completion = {
        border = "rounded",
        col_offset = 0,
        scrollbar = true,
        scrolloff = 0,
        side_padding = 1,
        winhighlight = "Normal:Normal,FloatBorder:Normal,CursorLine:Visual,Search:None",
        zindex = 1001,
      },
      documentation = {
        border = "rounded",
        col_offset = 0,
        scrollbar = true,
        scrolloff = 0,
        side_padding = 1,
        winhighlight = "Normal:Normal,FloatBorder:Normal,CursorLine:Visual,Search:None",
        zindex = 1001,
      },
    },
  },
  comment = {
    active = true,
    extra = {
      above = "gcO",
      below = "gco",
      eol = "gcA",
    },
    ignore = "^$",
    mappings = {
      basic = true,
      extra = true,
    },
    opleader = {
      block = "gb",
      line = "gc",
    },
    padding = true,
    pre_hook = "<function 25>",
    sticky = true,
    toggler = {
      block = "gbc",
      line = "gcc",
    },
  },
  dap = {
    active = true,
    breakpoint = {
      linehl = "",
      numhl = "",
      text = "",
      texthl = "DiagnosticSignError",
    },
    breakpoint_rejected = {
      linehl = "",
      numhl = "",
      text = "",
      texthl = "DiagnosticSignError",
    },
    log = {
      level = "info",
    },
    stopped = {
      linehl = "Visual",
      numhl = "DiagnosticSignWarn",
      text = "",
      texthl = "DiagnosticSignWarn",
    },
    ui = {
      auto_open = true,
      config = {
        controls = {
          element = "repl",
          enabled = true,
          icons = {
            pause = "",
            play = "",
            run_last = "",
            step_back = "",
            step_into = "",
            step_out = "",
            step_over = "",
            terminate = "",
          },
        },
        element_mappings = {},
        expand_lines = true,
        floating = {
          border = "rounded",
          mappings = {
            close = { "q", "<Esc>" },
          },
          max_height = 0.9,
          max_width = 0.5,
        },
        icons = {
          circular = "",
          collapsed = "",
          expanded = "",
        },
        layouts = {
          {
            elements = {
              {
                id = "scopes",
                size = 0.33,
              },
              {
                id = "breakpoints",
                size = 0.17,
              },
              {
                id = "stacks",
                size = 0.25,
              },
              {
                id = "watches",
                size = 0.25,
              },
            },
            position = "right",
            size = 0.33,
          },
          {
            elements = {
              {
                id = "repl",
                size = 0.45,
              },
              {
                id = "console",
                size = 0.55,
              },
            },
            position = "bottom",
            size = 0.27,
          },
        },
        mappings = {
          edit = "e",
          expand = { "<CR>", "<2-LeftMouse>" },
          open = "o",
          remove = "d",
          repl = "r",
          toggle = "t",
        },
        render = {
          max_value_lines = 100,
        },
        windows = {
          indent = 1,
        },
      },
      notify = {
        threshold = 2,
      },
    },
  },
  dashboard = {
    ["<metatable>"] = {
      __newindex = "<function 26>",
    },
  },
  gitsigns = {
    active = true,
    opts = {
      attach_to_untracked = true,
      current_line_blame = false,
      current_line_blame_formatter = "<author>, <author_time:%Y-%m-%d> - <summary>",
      current_line_blame_opts = {
        delay = 1000,
        ignore_whitespace = false,
        virt_text = true,
        virt_text_pos = "eol",
      },
      linehl = false,
      max_file_length = 40000,
      numhl = false,
      preview_config = {
        border = "rounded",
        col = 1,
        relative = "cursor",
        row = 0,
        style = "minimal",
      },
      sign_priority = 6,
      signcolumn = true,
      signs = {
        add = {
          hl = "GitSignsAdd",
          linehl = "GitSignsAddLn",
          numhl = "GitSignsAddNr",
          text = "▎",
        },
        change = {
          hl = "GitSignsChange",
          linehl = "GitSignsChangeLn",
          numhl = "GitSignsChangeNr",
          text = "▎",
        },
        changedelete = {
          hl = "GitSignsChange",
          linehl = "GitSignsChangeLn",
          numhl = "GitSignsChangeNr",
          text = "▎",
        },
        delete = {
          hl = "GitSignsDelete",
          linehl = "GitSignsDeleteLn",
          numhl = "GitSignsDeleteNr",
          text = "󰐊",
        },
        topdelete = {
          hl = "GitSignsDelete",
          linehl = "GitSignsDeleteLn",
          numhl = "GitSignsDeleteNr",
          text = "󰐊",
        },
      },
      update_debounce = 200,
      watch_gitdir = {
        follow_files = true,
        interval = 1000,
      },
      word_diff = false,
      yadm = {
        enable = false,
      },
    },
  },
  illuminate = {
    active = true,
    options = {
      delay = 120,
      filetype_overrides = {},
      filetypes_allowlist = {},
      filetypes_denylist = { "dirvish", "fugitive", "alpha", "NvimTree", "lazy", "neogitstatus", "Trouble", "lir",
        "Outline", "spectre_panel", "toggleterm", "DressingSelect", "TelescopePrompt" },
      modes_allowlist = {},
      modes_denylist = {},
      providers = { "lsp", "treesitter", "regex" },
      providers_regex_syntax_allowlist = {},
      providers_regex_syntax_denylist = {},
      under_cursor = true,
    },
  },
  indentlines = {
    active = true,
    options = {
      buftype_exclude = { "terminal", "nofile" },
      char = "▏",
      context_char = "▏",
      enabled = true,
      filetype_exclude = { "help", "startify", "dashboard", "lazy", "neogitstatus", "NvimTree", "Trouble", "text" },
      show_current_context = true,
      show_first_indent_level = true,
      show_trailing_blankline_indent = false,
      use_treesitter = true,
    },
  },
  lazy = {
    opts = {
      install = {
        colorscheme = { "gruvbox-material", "lunar", "habamax", "desert" },
      },
    },
  },
  lir = {
    active = true,
    devicons = {
      enable = true,
      highlight_dirname = true,
    },
    float = {
      curdir_window = {
        enable = false,
        highlight_dirname = true,
      },
      win_opts = "<function 27>",
      winblend = 0,
    },
    hide_cursor = false,
    icon = "",
    ignore = {},
    mappings = {
      ["<C-s>"] = "<function 28>",
      ["<C-t>"] = "<function 29>",
      ["<CR>"] = "<function 30>",
      ["@"] = "<function 31>",
      A = "<function 32>",
      J = "<function 33>",
      Y = "<function 34>",
      a = "<function 35>",
      c = "<function 36>",
      d = "<function 37>",
      h = "<function 38>",
      i = "<function 39>",
      l = "<function 40>",
      p = "<function 41>",
      q = "<function 42>",
      r = "<function 43>",
      v = "<function 44>",
      x = "<function 45>",
    },
    on_init = "<function 46>",
    show_hidden_files = false,
  },
  lualine = {
    active = true,
    extensions = {},
    inactive_sections = {
      lualine_a = {
        {
          "<function 47>",
          color = {},
          padding = {
            left = 0,
            right = 0,
          },
        },
      },
      lualine_b = {
        {
          "b:gitsigns_head",
          color = {
            gui = "bold",
          },
          icon = "%#SLGitIcon#%*%#SLBranchName#",
        },
      },
      lualine_c = {
        {
          "diff",
          diff_color = {
            added = {
              fg = "#98be65",
            },
            modified = {
              fg = "#ECBE7B",
            },
            removed = {
              fg = "#ec5f67",
            },
          },
          padding = {
            left = 2,
            right = 1,
          },
          source = "<function 48>",
          symbols = {
            added = " ",
            modified = " ",
            removed = " ",
          },
        },
        {
          "<function 49>",
          color = {
            fg = "#98be65",
          },
          cond = "<function 50>",
        },
      },
      lualine_x = {
        {
          "diagnostics",
          sources = { "nvim_diagnostic" },
          symbols = {
            error = " ",
            hint = " ",
            info = " ",
            warn = " ",
          },
        },
        {
          "<function 51>",
          color = {
            gui = "bold",
          },
          cond = "<function 50>",
        },
        {
          "<function 52>",
          padding = 1,
        },
        {
          "filetype",
          padding = {
            left = 1,
            right = 1,
          },
        },
      },
      lualine_y = {
        { "location" },
      },
      lualine_z = {
        {
          "progress",
          color = {},
          fmt = "<function 53>",
        },
      },
    },
    options = {
      component_separators = {
        left = "",
        right = "",
      },
      disabled_filetypes = {
        statusline = { "alpha" },
      },
      globalstatus = true,
      icons_enabled = true,
      section_separators = {
        left = "",
        right = "",
      },
      theme = "auto",
    },
    sections = {
      lualine_a = { "<table 1>" },
      lualine_b = { "<table 2>" },
      lualine_c = { "<table 3>", "<table 4>" },
      lualine_x = { "<table 5>", "<table 6>", "<table 7>", "<table 8>" },
      lualine_y = { "<table 9>" },
      lualine_z = { "<table 10>" },
    },
    style = "lvim",
    tabline = {},
  },
  luasnip = {
    sources = {
      friendly_snippets = true,
    },
  },
  mason = {
    PATH = "skip",
    github = {
      download_url_template = "https://github.com/%s/releases/download/%s/%s",
    },
    icons = {
      package_installed = "◍",
      package_pending = "◍",
      package_uninstalled = "◍",
    },
    install_root_dir = "/home/bukzor/.local/share/lvim/mason",
    log_level = 2,
    max_concurrent_installers = 4,
    pip = {
      install_args = {},
      upgrade_pip = false,
    },
    providers = { "mason.providers.registry-api", "mason.providers.client" },
    registries = { "lua:mason-registry.index", "github:mason-org/mason-registry" },
    ui = {
      border = "rounded",
      check_outdated_packages_on_open = true,
      height = 0.9,
      keymaps = {
        apply_language_filter = "<C-f>",
        cancel_installation = "<C-c>",
        check_outdated_packages = "C",
        check_package_version = "c",
        install_package = "i",
        toggle_package_expand = "<CR>",
        uninstall_package = "X",
        update_all_packages = "U",
        update_package = "u",
      },
      width = 0.8,
    },
  },
  notify = {
    ["<metatable>"] = {
      __newindex = "<function 54>",
    },
  },
  nvimtree = {
    active = true,
    setup = {
      actions = {
        change_dir = {
          enable = true,
          global = false,
          restrict_above_cwd = false,
        },
        expand_all = {
          exclude = {},
          max_folder_discovery = 300,
        },
        file_popup = {
          open_win_config = {
            border = "shadow",
            col = 1,
            relative = "cursor",
            row = 1,
            style = "minimal",
          },
        },
        open_file = {
          quit_on_open = false,
          resize_window = false,
          window_picker = {
            chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
            enable = true,
            exclude = {
              buftype = { "nofile", "terminal", "help" },
              filetype = { "notify", "lazy", "qf", "diff", "fugitive", "fugitiveblame" },
            },
            picker = "default",
          },
        },
        remove_file = {
          close_window = true,
        },
        use_system_clipboard = true,
      },
      auto_reload_on_write = false,
      diagnostics = {
        debounce_delay = 50,
        enable = true,
        icons = {
          error = "",
          hint = "",
          info = "",
          warning = "",
        },
        severity = {
          max = 1,
          min = 4,
        },
        show_on_dirs = false,
        show_on_open_dirs = true,
      },
      disable_netrw = false,
      filesystem_watchers = {
        debounce_delay = 50,
        enable = true,
        ignore_dirs = {},
      },
      filters = {
        custom = { "node_modules", "\\.cache" },
        dotfiles = false,
        exclude = {},
        git_clean = false,
        git_ignored = false,
        no_buffer = false,
      },
      git = {
        enable = true,
        show_on_dirs = true,
        show_on_open_dirs = true,
        timeout = 200,
      },
      hijack_cursor = false,
      hijack_directories = {
        auto_open = true,
        enable = false,
      },
      hijack_netrw = true,
      hijack_unnamed_buffer_when_opening = false,
      live_filter = {
        always_show_folders = true,
        prefix = "[FILTER]: ",
      },
      log = {
        enable = false,
        truncate = false,
        types = {
          all = false,
          config = false,
          copy_paste = false,
          dev = false,
          diagnostics = false,
          git = false,
          profile = false,
          watcher = false,
        },
      },
      notify = {
        threshold = 2,
      },
      on_attach = "<function 55>",
      prefer_startup_root = false,
      reload_on_bufenter = false,
      renderer = {
        add_trailing = false,
        full_name = false,
        group_empty = false,
        highlight_git = true,
        highlight_opened_files = "none",
        icons = {
          git_placement = "before",
          glyphs = {
            bookmark = "",
            default = "",
            folder = {
              arrow_closed = "",
              arrow_open = "",
              default = "󰉋",
              empty = "",
              empty_open = "",
              open = "",
              symlink = "",
              symlink_open = "",
            },
            git = {
              deleted = "",
              ignored = "◌",
              renamed = "",
              staged = "S",
              unmerged = "",
              unstaged = "",
              untracked = "U",
            },
            symlink = "",
          },
          padding = " ",
          show = {
            file = true,
            folder = true,
            folder_arrow = true,
            git = true,
          },
          symlink_arrow = " ➛ ",
          webdev_colors = true,
        },
        indent_markers = {
          enable = false,
          icons = {
            corner = "└",
            edge = "│",
            item = "│",
            none = " ",
          },
          inline_arrows = true,
        },
        indent_width = 2,
        root_folder_label = ":t",
        special_files = { "Cargo.toml", "Makefile", "README.md", "readme.md" },
        symlink_destination = true,
      },
      respect_buf_cwd = true,
      root_dirs = {},
      select_prompts = false,
      sort = {
        sorter = "name",
      },
      sync_root_with_cwd = true,
      system_open = {
        args = {},
      },
      tab = {
        sync = {
          close = false,
          ignore = {},
          open = false,
        },
      },
      trash = {
        cmd = "trash",
      },
      ui = {
        confirm = {
          trash = true,
        },
      },
      update_focused_file = {
        enable = false,
        ignore_list = {},
        update_root = true,
      },
      view = {
        centralize_selection = true,
        debounce_delay = 15,
        float = {
          enable = false,
          open_win_config = {
            border = "rounded",
            col = 1,
            height = 30,
            relative = "editor",
            row = 1,
            width = 30,
          },
          quit_on_focus_loss = true,
        },
        hide_root_folder = false,
        number = false,
        preserve_window_proportions = false,
        relativenumber = false,
        side = "left",
        signcolumn = "yes",
        width = 30,
      },
    },
  },
  project = {
    active = true,
    datapath = "/home/bukzor/.cache/lvim",
    detection_methods = { "pattern" },
    exclude_dirs = {},
    ignore_lsp = {},
    manual_mode = true,
    patterns = { ".git", "_darcs", ".hg", ".bzr", ".svn", "Makefile", "package.json", "pom.xml" },
    scope_chdir = "global",
    show_hidden = false,
    silent_chdir = true,
  },
  telescope = {
    active = true,
    defaults = {
      border = {},
      color_devicons = true,
      entry_prefix = "  ",
      file_ignore_patterns = {},
      initial_mode = "insert",
      layout_config = {},
      mappings = {
        i = {
          ["<C-c>"] = "<function 56>",
          ["<C-j>"] = "<function 57>",
          ["<C-k>"] = "<function 58>",
          ["<C-n>"] = "<function 59>",
          ["<C-p>"] = "<function 60>",
          ["<C-q>"] = "<function 61>",
          ["<CR>"] = "<function 62>",
        },
        n = {
          ["<C-n>"] = "<function 63>",
          ["<C-p>"] = "<function 64>",
          ["<C-q>"] = "<function 65>",
        },
      },
      path_display = { "smart" },
      prompt_prefix = " ",
      selection_caret = " ",
      selection_strategy = "reset",
      set_env = {
        COLORTERM = "truecolor",
      },
      vimgrep_arguments = { "rg", "--color=never", "--no-heading", "--with-filename", "--line-number", "--column",
        "--smart-case", "--hidden", "--glob=!.git/" },
      winblend = 0,
    },
    extensions = {
      fzf = {
        case_mode = "smart_case",
        fuzzy = true,
        override_file_sorter = true,
        override_generic_sorter = true,
      },
    },
    pickers = {
      buffers = {
        initial_mode = "normal",
        mappings = {
          i = {
            ["<C-d>"] = "<function 66>",
          },
          n = {
            dd = "<function 67>",
          },
        },
      },
      colorscheme = {
        enable_preview = true,
      },
      find_files = {
        hidden = true,
      },
      git_files = {
        hidden = true,
        show_untracked = true,
      },
      grep_string = {
        only_sort_text = true,
      },
      live_grep = {
        only_sort_text = true,
      },
      planets = {
        show_moon = true,
        show_pluto = true,
      },
    },
    theme = "dropdown",
  },
  terminal = {
    active = true,
    close_on_exit = true,
    direction = "float",
    execs = {
      {
        [2] = "<M-1>",
        [3] = "Horizontal Terminal",
        [4] = "horizontal",
        [5] = 0.3,
      },
      {
        [2] = "<M-2>",
        [3] = "Vertical Terminal",
        [4] = "vertical",
        [5] = 0.4,
      },
      {
        [2] = "<M-3>",
        [3] = "Float Terminal",
        [4] = "float",
      },
    },
    float_opts = {
      border = "curved",
      highlights = {
        background = "Normal",
        border = "Normal",
      },
      winblend = 0,
    },
    hide_numbers = true,
    insert_mappings = true,
    open_mapping = "<c-\\>",
    persist_size = false,
    shade_filetypes = {},
    shade_terminals = true,
    shading_factor = 2,
    size = 20,
    start_in_insert = true,
  },
  theme = {
    lunar = {
      options = {},
    },
    name = "lunar",
    options = {
      ["<metatable>"] = {
        __newindex = "<function 68>",
      },
    },
    tokyonight = {
      options = {
        day_brightness = 0.3,
        dim_inactive = false,
        hide_inactive_statusline = false,
        lualine_bold = false,
        on_highlights = "<function 69>",
        sidebars = { "qf", "vista_kind", "terminal", "packer", "spectre_panel", "NeogitStatus", "help" },
        style = "night",
        styles = {
          comments = {
            italic = true,
          },
          floats = "dark",
          functions = {},
          keywords = {
            italic = true,
          },
          sidebars = "dark",
          variables = {},
        },
        terminal_colors = true,
        transparent = false,
        use_background = true,
      },
    },
  },
  treesitter = {
    auto_install = true,
    autotag = {
      enable = false,
    },
    context_commentstring = {
      config = {
        css = "/* %s */",
        html = "<!-- %s -->",
        json = "",
        scss = "/* %s */",
        svelte = "<!-- %s -->",
        typescript = "// %s",
        vue = "<!-- %s -->",
      },
      enable = true,
      enable_autocmd = false,
    },
    ensure_installed = { "comment", "markdown_inline", "regex" },
    highlight = {
      additional_vim_regex_highlighting = false,
      disable = "<function 70>",
      enable = true,
    },
    ignore_install = {},
    indent = {
      disable = { "yaml", "python" },
      enable = true,
    },
    matchup = {
      enable = false,
    },
    playground = {
      disable = {},
      enable = false,
      keybindings = {
        focus_language = "f",
        goto_node = "<cr>",
        show_help = "?",
        toggle_anonymous_nodes = "a",
        toggle_hl_groups = "i",
        toggle_injected_languages = "t",
        toggle_language_display = "I",
        toggle_query_editor = "o",
        unfocus_language = "F",
        update = "R",
      },
      persist_queries = false,
      updatetime = 25,
    },
    rainbow = {
      enable = false,
      extended_mode = true,
      max_file_lines = 1000,
    },
    sync_install = false,
    textobjects = {
      select = {
        enable = false,
      },
      swap = {
        enable = false,
      },
    },
    textsubjects = {
      enable = false,
      keymaps = {
        ["."] = "textsubjects-smart",
        [";"] = "textsubjects-big",
      },
    },
  },
  which_key = {
    active = true,
    mappings = {
      ["/"] = { "<Plug>(comment_toggle_linewise_current)", "Comment toggle current line" },
      [";"] = { "<cmd>Alpha<CR>", "Dashboard" },
      L = {
        I = { "<cmd>lua require('lvim.core.telescope.custom-finders').view_lunarvim_changelog()<cr>",
          "View LunarVim's changelog" },
        c = { "<cmd>edit /home/bukzor/.config/lvim/config.lua<cr>", "Edit config.lua" },
        d = { "<cmd>LvimDocs<cr>", "View LunarVim's docs" },
        f = { "<cmd>lua require('lvim.core.telescope.custom-finders').find_lunarvim_files()<cr>", "Find LunarVim files" },
        g = { "<cmd>lua require('lvim.core.telescope.custom-finders').grep_lunarvim_files()<cr>", "Grep LunarVim files" },
        i = { "<cmd>lua require('lvim.core.info').toggle_popup(vim.bo.filetype)<cr>", "Toggle LunarVim Info" },
        k = { "<cmd>Telescope keymaps<cr>", "View LunarVim's keymappings" },
        l = {
          D = { "<cmd>lua vim.fn.execute('edit ' .. require('lvim.core.log').get_path())<cr>",
            "Open the default logfile" },
          L = { "<cmd>lua vim.fn.execute('edit ' .. vim.lsp.get_log_path())<cr>", "Open the LSP logfile" },
          N = { "<cmd>edit $NVIM_LOG_FILE<cr>", "Open the Neovim logfile" },
          d = { "<cmd>lua require('lvim.core.terminal').toggle_log_view(require('lvim.core.log').get_path())<cr>",
            "view default log" },
          l = { "<cmd>lua require('lvim.core.terminal').toggle_log_view(vim.lsp.get_log_path())<cr>", "view lsp log" },
          n = { "<cmd>lua require('lvim.core.terminal').toggle_log_view(os.getenv('NVIM_LOG_FILE'))<cr>",
            "view neovim log" },
          name = "+logs",
        },
        name = "+LunarVim",
        r = { "<cmd>LvimReload<cr>", "Reload LunarVim's configuration" },
        u = { "<cmd>LvimUpdate<cr>", "Update LunarVim" },
      },
      T = {
        i = { ":TSConfigInfo<cr>", "Info" },
        name = "Treesitter",
      },
      b = {
        D = { "<cmd>BufferLineSortByDirectory<cr>", "Sort by directory" },
        L = { "<cmd>BufferLineSortByExtension<cr>", "Sort by language" },
        W = { "<cmd>noautocmd w<cr>", "Save without formatting (noautocmd)" },
        b = { "<cmd>BufferLineCyclePrev<cr>", "Previous" },
        e = { "<cmd>BufferLinePickClose<cr>", "Pick which buffer to close" },
        f = { "<cmd>Telescope buffers previewer=false<cr>", "Find" },
        h = { "<cmd>BufferLineCloseLeft<cr>", "Close all to the left" },
        j = { "<cmd>BufferLinePick<cr>", "Jump" },
        l = { "<cmd>BufferLineCloseRight<cr>", "Close all to the right" },
        n = { "<cmd>BufferLineCycleNext<cr>", "Next" },
        name = "Buffers",
      },
      c = { "<cmd>BufferKill<CR>", "Close Buffer" },
      d = {
        C = { "<cmd>lua require'dap'.run_to_cursor()<cr>", "Run To Cursor" },
        U = { "<cmd>lua require'dapui'.toggle({reset = true})<cr>", "Toggle UI" },
        b = { "<cmd>lua require'dap'.step_back()<cr>", "Step Back" },
        c = { "<cmd>lua require'dap'.continue()<cr>", "Continue" },
        d = { "<cmd>lua require'dap'.disconnect()<cr>", "Disconnect" },
        g = { "<cmd>lua require'dap'.session()<cr>", "Get Session" },
        i = { "<cmd>lua require'dap'.step_into()<cr>", "Step Into" },
        name = "Debug",
        o = { "<cmd>lua require'dap'.step_over()<cr>", "Step Over" },
        p = { "<cmd>lua require'dap'.pause()<cr>", "Pause" },
        q = { "<cmd>lua require'dap'.close()<cr>", "Quit" },
        r = { "<cmd>lua require'dap'.repl.toggle()<cr>", "Toggle Repl" },
        s = { "<cmd>lua require'dap'.continue()<cr>", "Start" },
        t = { "<cmd>lua require'dap'.toggle_breakpoint()<cr>", "Toggle Breakpoint" },
        u = { "<cmd>lua require'dap'.step_out()<cr>", "Step Out" },
      },
      e = { "<cmd>NvimTreeToggle<CR>", "Explorer" },
      f = { "<function 71>", "Find File" },
      g = {
        C = { "<cmd>Telescope git_bcommits<cr>", "Checkout commit(for current file)" },
        R = { "<cmd>lua require 'gitsigns'.reset_buffer()<cr>", "Reset Buffer" },
        b = { "<cmd>Telescope git_branches<cr>", "Checkout branch" },
        c = { "<cmd>Telescope git_commits<cr>", "Checkout commit" },
        d = { "<cmd>Gitsigns diffthis HEAD<cr>", "Git Diff" },
        g = { "<cmd>lua require 'lvim.core.terminal'.lazygit_toggle()<cr>", "Lazygit" },
        j = { "<cmd>lua require 'gitsigns'.next_hunk({navigation_message = false})<cr>", "Next Hunk" },
        k = { "<cmd>lua require 'gitsigns'.prev_hunk({navigation_message = false})<cr>", "Prev Hunk" },
        l = { "<cmd>lua require 'gitsigns'.blame_line()<cr>", "Blame" },
        name = "Git",
        o = { "<cmd>Telescope git_status<cr>", "Open changed file" },
        p = { "<cmd>lua require 'gitsigns'.preview_hunk()<cr>", "Preview Hunk" },
        r = { "<cmd>lua require 'gitsigns'.reset_hunk()<cr>", "Reset Hunk" },
        s = { "<cmd>lua require 'gitsigns'.stage_hunk()<cr>", "Stage Hunk" },
        u = { "<cmd>lua require 'gitsigns'.undo_stage_hunk()<cr>", "Undo Stage Hunk" },
      },
      h = { "<cmd>nohlsearch<CR>", "No Highlight" },
      l = {
        I = { "<cmd>Mason<cr>", "Mason Info" },
        S = { "<cmd>Telescope lsp_dynamic_workspace_symbols<cr>", "Workspace Symbols" },
        a = { "<cmd>lua vim.lsp.buf.code_action()<cr>", "Code Action" },
        d = { "<cmd>Telescope diagnostics bufnr=0 theme=get_ivy<cr>", "Buffer Diagnostics" },
        e = { "<cmd>Telescope quickfix<cr>", "Telescope Quickfix" },
        f = { "<cmd>lua require('lvim.lsp.utils').format()<cr>", "Format" },
        i = { "<cmd>LspInfo<cr>", "Info" },
        j = { "<cmd>lua vim.diagnostic.goto_next()<cr>", "Next Diagnostic" },
        k = { "<cmd>lua vim.diagnostic.goto_prev()<cr>", "Prev Diagnostic" },
        l = { "<cmd>lua vim.lsp.codelens.run()<cr>", "CodeLens Action" },
        name = "LSP",
        q = { "<cmd>lua vim.diagnostic.setloclist()<cr>", "Quickfix" },
        r = { "<cmd>lua vim.lsp.buf.rename()<cr>", "Rename" },
        s = { "<cmd>Telescope lsp_document_symbols<cr>", "Document Symbols" },
        w = { "<cmd>Telescope diagnostics<cr>", "Diagnostics" },
      },
      p = {
        S = { "<cmd>Lazy clear<cr>", "Status" },
        c = { "<cmd>Lazy clean<cr>", "Clean" },
        d = { "<cmd>Lazy debug<cr>", "Debug" },
        i = { "<cmd>Lazy install<cr>", "Install" },
        l = { "<cmd>Lazy log<cr>", "Log" },
        name = "Plugins",
        p = { "<cmd>Lazy profile<cr>", "Profile" },
        s = { "<cmd>Lazy sync<cr>", "Sync" },
        u = { "<cmd>Lazy update<cr>", "Update" },
      },
      q = { "<cmd>confirm q<CR>", "Quit" },
      s = {
        C = { "<cmd>Telescope commands<cr>", "Commands" },
        H = { "<cmd>Telescope highlights<cr>", "Find highlight groups" },
        M = { "<cmd>Telescope man_pages<cr>", "Man Pages" },
        R = { "<cmd>Telescope registers<cr>", "Registers" },
        b = { "<cmd>Telescope git_branches<cr>", "Checkout branch" },
        c = { "<cmd>Telescope colorscheme<cr>", "Colorscheme" },
        f = { "<cmd>Telescope find_files<cr>", "Find File" },
        h = { "<cmd>Telescope help_tags<cr>", "Find Help" },
        k = { "<cmd>Telescope keymaps<cr>", "Keymaps" },
        l = { "<cmd>Telescope resume<cr>", "Resume last search" },
        name = "Search",
        p = { "<cmd>lua require('telescope.builtin').colorscheme({enable_preview = true})<cr>",
          "Colorscheme with Preview" },
        r = { "<cmd>Telescope oldfiles<cr>", "Open Recent File" },
        t = { "<cmd>Telescope live_grep<cr>", "Text" },
      },
      w = { "<cmd>w!<CR>", "Save" },
    },
    opts = {
      mode = "n",
      noremap = true,
      nowait = true,
      prefix = "<leader>",
      silent = true,
    },
    setup = {
      disable = {
        buftypes = {},
        filetypes = { "TelescopePrompt" },
      },
      hidden = { "<silent>", "<cmd>", "<Cmd>", "<CR>", "call", "lua", "^:", "^ " },
      icons = {
        breadcrumb = "»",
        group = "",
        separator = "",
      },
      ignore_missing = true,
      key_labels = {},
      layout = {
        align = "left",
        height = {
          max = 25,
          min = 4,
        },
        spacing = 3,
        width = {
          max = 50,
          min = 20,
        },
      },
      operators = {
        gc = "Comments",
      },
      plugins = {
        marks = false,
        presets = {
          g = false,
          motions = false,
          nav = false,
          operators = false,
          text_objects = false,
          windows = false,
          z = false,
        },
        registers = false,
        spelling = {
          enabled = true,
          suggestions = 20,
        },
      },
      popup_mappings = {
        scroll_down = "<c-d>",
        scroll_up = "<c-u>",
      },
      show_help = true,
      show_keys = true,
      triggers = "auto",
      triggers_blacklist = {
        i = { "j", "k" },
        v = { "j", "k" },
      },
      window = {
        border = "single",
        margin = { 1, 0, 1, 0 },
        padding = { 2, 2, 2, 2 },
        position = "bottom",
        winblend = 0,
      },
    },
    vmappings = {
      ["/"] = { "<Plug>(comment_toggle_linewise_visual)", "Comment toggle linewise (visual)" },
      l = {
        a = { "<cmd>lua vim.lsp.buf.code_action()<cr>", "Code Action" },
        name = "LSP",
      },
    },
    vopts = {
      mode = "v",
      noremap = true,
      nowait = true,
      prefix = "<leader>",
      silent = true,
    },
  },
}
