# https://rasika90.medium.com/how-i-saved-tons-of-gbs-with-https-caching-41550b4ada8a
[global]
###proxy = 127.0.0.1:3128
###cert = /opt/homebrew/etc/ca-certificates/squid-self-signed.pem

# vim:ft=ini:
