#!/bin/sh
# $Id: //depot/tools/aticad/1.0/src/sysadmin/svcpdcad.xstartup#2 $
# Red Hat Linux 3.0 VNC session startup script

# General section
unset SESSION_MANAGER
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey

#set VNC to poll for gVIM clipboard changes
/tool/pandora/bin/vncconfig -poll=10 2>/dev/null >&2 &



# Pick ONE (and only one) of the following:

# For a GNOME Desktop (default)
exec /etc/X11/xinit/xinitrc

# For a KDE Desktop (alternative)
# exec /usr/bin/startkde

# For a xfce Desktop (faster)
# exec /usr/bin/startxfce4

# For a twm Desktop (minimalist)
# xterm -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
# exec /usr/X11R6/bin/twm
