#!/bin/bash
set -eo pipefail
HERE="$(cd "$(dirname "$0")"; pwd)"

lock_id=$("$HERE/"tf-lock-id) && status=$? || status=$?

if (( status == 0 )); then
  terraform force-unlock -force "$lock_id"
elif (( status == 2 )); then
  # "(terraform state not locked)"
  : already done!
  exit 0
else
  # surface any unexpected errors
  cat >&2 <<< "$lock_id"
  exit "$status"
fi
