name: Check sh

on: [push, pull_request]

jobs:
  test:
    name: shell test matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install shells
        run: sudo apt-get update && sudo apt-get install -y dash busybox zsh

      - name: Install redo
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install redo
          echo "/home/linuxbrew/.linuxbrew/bin" >> "$GITHUB_PATH"

      - name: Run shell test matrix
        run: redo -j"$(nproc)" test
