name: Check sh

on: [push, pull_request]

jobs:
  test:
    name: shell test matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install shells
        run: sudo apt-get update && sudo apt-get install -y dash busybox zsh

      - name: Install redo
        run: brew install redo

      - name: Run shell test matrix
        run: redo -j"$(nproc)" test
